name: Lint
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'ci/**'
      - '.github/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '.github/**'
      - '*.md'

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.50.1

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact